package entity;

import java.util.Set;

/**
 * AreaType generated by MyEclipse Persistence Tools
 */

public class AreaType implements java.io.Serializable {

	// Fields

	private Integer gid;
	private String area;

	// Constructors

	/** default constructor */
	public AreaType() {
	}

	/** minimal constructor */
	public AreaType(String area) {
		this.area = area;
	}

	/** full constructor */
	public AreaType(String area, Set leaseRooms, Set begRents) {
		this.area = area;

	}

	// Property accessors

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}