package entity;

/**
 * ImageTable generated by MyEclipse Persistence Tools
 */

public class ImageTable implements java.io.Serializable {

	// Fields

	private Integer id;
	private Leaseshuiguo leaseShuiguo;
	private String image;

	// Constructors

	/** default constructor */
	public ImageTable() {
	}

	/** minimal constructor */
	public ImageTable(Leaseshuiguo leaseShuiguo) {
		this.leaseShuiguo = leaseShuiguo;
	}

	/** full constructor */
	public ImageTable(Leaseshuiguo leaseShuiguo, String image) {
		this.leaseShuiguo = leaseShuiguo;
		this.image = image;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Leaseshuiguo getLeaseShuiguo() {
		return this.leaseShuiguo;
	}

	public void setLeaseShuiguo(Leaseshuiguo leaseShuiguo) {
		this.leaseShuiguo = leaseShuiguo;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}