package entity;

import java.util.Set;

/**
 * HouseType generated by MyEclipse Persistence Tools
 */

public class ShuiguoType implements java.io.Serializable {

	// Fields

	private Integer id;
	private String type;

	// Constructors

	/** default constructor */
	public ShuiguoType() {
	}

	/** minimal constructor */
	public ShuiguoType(String type) {
		this.type = type;
	}

	/** full constructor */
	public ShuiguoType(String type, Set leaseRooms, Set begRents) {
		this.type = type;

	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}



}