/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import server.BegRentServer;
import server.BusinessServer;
import server.LeaseShuiguoServer;
import server.UserInfoServer;
import server.UserServer;
import server.impl.BegRentServerImpl;
import server.impl.BusinessServerImpl;
import server.impl.LeaseShuiguoServerImpl;
import server.impl.UserInfoServerImpl;
import server.impl.UserServerImpl;
import struts.form.BusinessForm;
import struts.form.UsersInfoForm;
import bean.BegRentBean;
import bean.LeaseShuiguoBean;
import entity.Business;
import entity.Users;
import entity.UsersInfo;

/**
 * MyEclipse Struts Creation date: 06-26-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/usersInfo" name="usersInfoForm"
 *                input="/form/usersInfo.jsp" parameter="method" scope="request"
 *                validate="true"
 */
@Entity public class BusinessInfoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException
	 * @throws IOException
	 * @throws InvocationTargetException
	 * @throws IllegalAccessException
	 */
	
}