/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import bean.PublicBean;


import entity.Users;

import server.ChooseshuiguoServer;
import server.impl.ChooseShuiguoServerImpl;
import struts.form.ChooseShuiguoForm;

/**
 * @struts.action path="/chooseShuiguo" name="chooseShuiguoForm"
 *                input="/form/chooseShuiguo.jsp" scope="request" validate="true"
 */
@Entity public class ChooseShuiguoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addchooseshuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) 
			throws IOException{
		ChooseShuiguoForm chooseShuiguoForm = (ChooseShuiguoForm) form;// TODO
		// Auto-generated
		// method stub
		int lid = Integer.parseInt(request.getParameter("lid"));
		int uid = Integer.parseInt(request.getParameter("uid"));
		ChooseshuiguoServer chooseshuiguoServer = new ChooseShuiguoServerImpl();
		String msg = chooseshuiguoServer.add(lid, uid);
		request.setAttribute("msg", msg);
		PrintWriter out = response.getWriter();
		out.print("<script>");
		out.print("alert('"+msg+"');");
		out.print("window.location='chooseshuiguo.jsp';");

		out.print("</script>");
		return null;
	}

	public ActionForward delchooseshuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		ChooseShuiguoForm chooseShuiguoForm = (ChooseShuiguoForm) form;

		int id = Integer.parseInt(request.getParameter("id"));

		ChooseshuiguoServer chooseshuiguoServer = new ChooseShuiguoServerImpl();

		//chooseshuiguoServer.deletechooseshuiguo(id);

		PrintWriter out = response.getWriter();

		boolean falg = false;

		falg = chooseshuiguoServer.deletechooseshuiguo(id);

		if (falg = true) {

			out.print("<script>");
			out.print("alert('É¾³ý³É¹¦!!!');");
			out.print("window.location='chooseshuiguo.jsp';");

			out.print("</script>");
			return null;
		} else {

			out.print("<script>");
			out.print("alert('É¾³ýÊ§°Ü!!!');");
			out.print("window.location='chooseshuiguo.jsp';");
			out.print("</script>");
			return null;
		}

	}

	public ActionForward showChooseshuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		ChooseShuiguoForm chooseShuiguoForm = (ChooseShuiguoForm) form;
		ChooseshuiguoServer server = new ChooseShuiguoServerImpl();
		int showPage = chooseShuiguoForm.getShowPage(); 
        
		Users users=(Users)request.getSession().getAttribute("users");
		
		PublicBean bean=server.getByPage(showPage,users.getUid());  
		chooseShuiguoForm.setAllCount(bean.getAllCount());
		chooseShuiguoForm.setAllPage(bean.getAllPage());
		chooseShuiguoForm.setShowPage(bean.getShowPage());
		request.setAttribute("crlist", bean.getList());
		request.setAttribute("islist", "islist");
		return mapping.findForward("show");

	}
}