/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import server.AreaTypeServer;
import server.BusinessServer;
import server.LeaseShuiguoServer;
import server.ShuiguoTypeServer;
import server.ImageTableServer;
import server.LeaseShuiguoServer;
import server.UserServer;
import server.impl.AreaTypeServerImpl;
import server.impl.BusinessServerImpl;
import server.impl.LeaseShuiguoServerImpl;
import server.impl.ShuiguoTypeServerimpl;
import server.impl.ImageTableServerImpl;
import server.impl.LeaseShuiguoServerImpl;
import server.impl.UserServerImpl;
import struts.form.LeaseShuiguoForm;
import struts.form.LeaseShuiguoForm;
import bean.LeaseShuiguoBean;
import bean.LeaseShuiguoBean;
import bean.PublicBean;
import entity.AreaType;
import entity.Business;
import entity.ShuiguoType;
import entity.ImageTable;
import entity.Leaseshuiguo;
import entity.Users;

/**
 * MyEclipse Struts Creation date: 06-24-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/leaseShuiguo" name="leaseShuiguoForm" parameter="method"
 *                scope="request"
 */
@Entity public class LeaseshuiguoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	public void sel(HttpServletRequest request, HttpServletResponse response) {
		AreaTypeServer server = new AreaTypeServerImpl();
		ShuiguoTypeServer hserver = new ShuiguoTypeServerimpl();

		List<ShuiguoType> hlist = hserver.select(); // 品种
		List<AreaType> alist = server.selArea(); // 区域

		request.setAttribute("hlist", hlist);
		request.setAttribute("alist", alist);

	}

	// 审核
	public ActionForward toExamine(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		LeaseShuiguoForm leaseShuiguoForm = (LeaseShuiguoForm) form;

		int id = Integer.parseInt(request.getParameter("id"));
		int state = Integer.parseInt(request.getParameter("state"));
		LeaseShuiguoServer shuiguoServer = new LeaseShuiguoServerImpl();
		Leaseshuiguo leaseShuiguo = shuiguoServer.getShuiguo(id);
		leaseShuiguo.setState(state);

		if (shuiguoServer.update(leaseShuiguo)) {
			response.getWriter().print("<script>");
			response.getWriter().print("alert('审核完成！');");
			response
					.getWriter()
					.print(
							"window.location='leaseShuiguo.do?method=showShuiguoAdmin&showPage=1';");
			response.getWriter().print("</script>");
		} else {
			response.getWriter().print("<script>");
			response.getWriter().print("alert('审核失败！');");
			response
					.getWriter()
					.print(
							"window.location='leaseShuiguo.do?method=showShuiguoAdmin&showPage=1';");
			response.getWriter().print("</script>");

		}

		return null;
	}

	public ActionForward selArea(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LeaseShuiguoForm leaseShuiguoForm = (LeaseShuiguoForm) form;
		sel(request, response);
		return mapping.findForward("ok");
	}

	// 添加
	public ActionForward addLease(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoForm leaseform = (LeaseShuiguoForm) form;

		LeaseShuiguoServer lserver = new LeaseShuiguoServerImpl();
		AreaTypeServer aserver = new AreaTypeServerImpl();
		ShuiguoTypeServer hserver = new ShuiguoTypeServerimpl();
		BusinessServer bserver = new BusinessServerImpl();

		Leaseshuiguo shuiguo = new Leaseshuiguo();
		BeanUtils.copyProperties(shuiguo, leaseform); // 复制javaBean 属性

		if (leaseform.getEsthments() != null) {// 运输方式
			String esthment = "";
			for (String ment : leaseform.getEsthments()) {
				esthment += ment + ",";
			}
			esthment = esthment.substring(0, esthment.length() - 1);
			shuiguo.setEsthment(esthment);
		}
		Business business = (Business) request.getSession().getAttribute("business");// 加载当前用户
		shuiguo.setTime(new Date().toLocaleString());
		shuiguo.setState(1); // 等待审核
		shuiguo.setAreaType(aserver.getthis(leaseform.getAreaId())); // 加载并设置一个区域对象
		shuiguo.setShuiguoType(hserver.getShuiguo_type(leaseform.getHtypeId())); // 加载并设置一个水果类别对象
		shuiguo.setBusiness(business);

		// 判断用户联系方式是否有改变
		if (!business.getBphone().equals(leaseform.getTelePhone())
				|| !business.getBemail().endsWith(leaseform.getEmail())) {
			// 有改变，修改当前用户信息
			business.setBphone(leaseform.getTelePhone());
			business.setBemail(leaseform.getEmail());
			bserver.update(business);
		}

		boolean isshuiguo = false;
		boolean isimg = true;
		int isimgCount = 0;

		// 获得上传文件保存在服务器上的文件夹路径
		String path = this.servlet.getServletContext()
				.getRealPath("/uploadIMG");

		for (int i = 0; i < leaseform.getFile().length; i++) {
			FormFile file = leaseform.getFile()[i];
			if (file != null && !file.getFileName().equals("")) { // 需要上传图片的情况

				String date = new SimpleDateFormat("yyyyMMddhhmmss")
						.format(new Date());
				String fileName = file.getFileName(); // 获得上传文件名
				fileName = business.getUname() + "_" + date
						+ fileName.substring(fileName.lastIndexOf(".")); // 重命名上传文件名

				if (isimgCount == 0) {
					shuiguo.setImg(fileName); // 设置封面
					isshuiguo = lserver.addShuiguo(shuiguo);// 添加该条房源信息
				}
				if (!isshuiguo) { // 水果信息添加失败，停止图片上传
					break;
				}
				// 获得上传文件数据
				byte[] data = file.getFileData();
				// 创建文件对象
				File uploadFile = new File(path + "\\" + fileName);
				// 创建文件输出流
				FileOutputStream stream = new FileOutputStream(uploadFile);
				stream.write(data);

				// 添加图片到数据库表
				ImageTableServer iserver = new ImageTableServerImpl();
				ImageTable image = new ImageTable();
				image.setImage(fileName);
				image.setLeaseShuiguo(shuiguo);
				if (!iserver.add(image)) { // 添加图片出错
					isimg = false;
					break;
				} else {
					isimgCount++; // 添加的图片数
				}

			}
		}

		if (isimgCount == 0) {// 不需要上传图片的情况，
			shuiguo.setImg("");
			isshuiguo = lserver.addShuiguo(shuiguo);// 直接添加该条房源信息
		}
		if (isshuiguo && isimg) { // 图片全部成功上传
			if (isimgCount == 0) { // 没有上传图片
				response.getWriter().print("<script>");
				response.getWriter().print("alert('发布水果信息成功！');");
				response.getWriter().print("window.location='shuiguo.jsp';");
				response.getWriter().print("</script>");

			} else { // 图片全部成功上传
				response.getWriter().print("<script>");
				response.getWriter().print("alert('发布水果信息成功！图片已被成功上传');");
				response.getWriter().print("window.location='shuiguo.jsp';");
				response.getWriter().print("</script>");
			}

		} else if (isshuiguo && isimg == false && isimgCount > 0) { // 部分图片上传成功
			response.getWriter().print("<script>");
			response.getWriter().print(
					"alert('发布水果信息成功！" + isimgCount + "张图片已被成功上传');");
			response.getWriter().print("window.location='shuiguo.jsp';");
			response.getWriter().print("</script>");
		} else if (isshuiguo && isimg == false && isimgCount == 0) { // 图片上传失败
			response.getWriter().print("<script>");
			response.getWriter().print("alert('发布水果信息成功！图片上传失败');");
			response.getWriter().print("window.location='shuiguo.jsp';");
			response.getWriter().print("</script>");
		} else { // 发布出租房源失败(图片不被上传)
			response.getWriter().print("<script>");
			response.getWriter().print("alert('发布水果信息失败，请重新再试！');");
			response.getWriter().print("window.history.go(-1);");
			response.getWriter().print("</script>");
		}

		return null;
	}

	// 分页查询所有水果销售信息信息(管理员后台)
	public ActionForward showShuiguoAdmin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws FileNotFoundException, IllegalAccessException,
			InvocationTargetException, IOException {
		int row = 8; // 每页所要显示的数据条数

		int state = 2;  //不显示审核未通过的
		show(row, state, form, request, response);// 调用show()方法，获得房源信息分页数据

		return mapping.findForward("showshuiguo");
	}

	// 获得水果信息分页数据
	public void show(int row, int state, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoForm leaseShuiguoForm = (LeaseShuiguoForm) form;
		LeaseShuiguoServer lserver = new LeaseShuiguoServerImpl();

		LeaseShuiguoBean lbean = new LeaseShuiguoBean(); // 条件javaBean
		lbean.setState(state);
		int showPage = leaseShuiguoForm.getShowPage(); // 获得所要显示的页码

		BeanUtils.copyProperties(lbean, leaseShuiguoForm); // 复制条件javabean

		if (row == 5) {
			int uid = ((Business) request.getSession().getAttribute("business"))
					.getBusId(); // 获得当前用户id
			lbean.setUid(uid); // 根据用户id查询分页
		}
		PublicBean bean = lserver.getByPage(showPage, row, lbean);
		List<Leaseshuiguo> lrList = bean.getList();

		request.setAttribute("showPage", showPage);
		request.setAttribute("allPage", bean.getAllPage());
		request.setAttribute("allCount", bean.getAllCount());
		request.setAttribute("rlList", bean.getList());
		request.setAttribute("lbean", lbean); // 存储条件

	}

	// 分页查询所有水果信息(用户后台)
	public ActionForward showShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws FileNotFoundException, IllegalAccessException,
			InvocationTargetException, IOException {
		int row = 5; // 每页所要显示的数据条数

		int state = 0;
		show(row, state, form, request, response);// 调用show()方法，获得房源信息分页数据
		request.setAttribute("islist", "is");
		return mapping.findForward("show");
	}

	// 分页查询所有水果销售信息(前台首页)
	public ActionForward showShuiguoIndex(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();
		int row = 8;
		int state = 3;
		show(row, state, form, request, response);// 调用show()方法，获得水果信息分页数据

		sel(request, response); // 获得区域和水果品种数据

		if (request.getSession().getAttribute("users") != null) { // 判断用户是否登录
			// 如果已登录，获得当前用户浏览过的水果信息
			getCookie(request, response);
		}else if(request.getSession().getAttribute("business") != null){
			List<Leaseshuiguo> list = server.topShuiguo(new LeaseShuiguoBean(), 5);
			request.setAttribute("list", list);
		
			return mapping.findForward("bindex");		
		}

		List<Leaseshuiguo> list = server.topShuiguo(new LeaseShuiguoBean(), 5);
		request.setAttribute("list", list);
	
		return mapping.findForward("index");
	}

	public ActionForward searchShuiguoIndex(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		String key = request.getParameter("title");
		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();
		int row = 8;
		int state = 3;
		show(row, state, form, request, response);// 调用show()方法，获得水果信息分页数据

		sel(request, response); // 获得区域和水果类别数据

		if (request.getSession().getAttribute("users") != null) { // 判断用户是否登录
			// 如果已登录，获得当前用户浏览过的水果信息
			getCookie(request, response);
		}else if(request.getSession().getAttribute("business") != null){
			List<Leaseshuiguo> list = server.topShuiguo(new LeaseShuiguoBean(), 5,key);
			request.setAttribute("list", list);
			return mapping.findForward("bindex");	
		}
        
		List<Leaseshuiguo> list = server.topShuiguo(new LeaseShuiguoBean(), 5,key);
		request.setAttribute("list", list);
		return mapping.findForward("index");
	}
	// 获得用户浏览过的水果信息
	public void getCookie(HttpServletRequest request,
			HttpServletResponse response) {
		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();
		int uid = ((Users) request.getSession().getAttribute("users")).getUid();// 获得当前登录用户id
		String cookieName = "shuiguoList" + uid; // cookie名
		Cookie cookies[] = request.getCookies();

		if (cookies != null) {
			Cookie cookie = null;
			for (Cookie c : cookies) {
				if (c.getName().equals(cookieName)) {
					cookie = c;
					break;
				}
			}
			if (cookie != null) {
				String strs[] = cookie.getValue().split(",");// 获得每一个水果id并存入数组
				List<Leaseshuiguo> cookieShuiguo = new ArrayList<Leaseshuiguo>();
				for (String str : strs) {
					// 加载水果信息
					Leaseshuiguo shuiguo = server.getShuiguo(Integer.parseInt(str));
					// 存入list集合
					if (shuiguo != null) {
						cookieShuiguo.add(shuiguo);
					}
				}
				request.setAttribute("cookieShuiguo", cookieShuiguo);
			}
		}

	}

	// 获得出售水果信息额及图片
	public Leaseshuiguo getisShuiguo(ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws IllegalAccessException,
			InvocationTargetException, FileNotFoundException, IOException {
		LeaseShuiguoForm leaseform = (LeaseShuiguoForm) form;

		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();
		ImageTableServer imgserver = new ImageTableServerImpl();

		int rid = leaseform.getId();
		Leaseshuiguo shuiguo = server.getShuiguo(rid); // 加载该水果对象
		List<ImageTable> img = imgserver.selImage(rid); // 获得图片集合
		int size = 0;
		if (img != null) {
			size = img.size();
		}
		request.setAttribute("image", img);

		request.setAttribute("imgSize", size);
		return shuiguo;

	}

	// 获得出租水果信息(前台查看)
	public ActionForward getleaseShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();

		Leaseshuiguo shuiguo = getisShuiguo(form, request, response);
		LeaseShuiguoBean bean = new LeaseShuiguoBean();
		bean.setUid(shuiguo.getBusiness().getBusId()); // 用户id,这里为房东
		bean.setId(shuiguo.getId());
		List<Leaseshuiguo> list = server.topShuiguo(bean, 8); // 获得该房东其他出租水果信息

		request.setAttribute("rlist", list);
		request.setAttribute("shuiguo", shuiguo);

		if (request.getSession().getAttribute("users") != null) { // 判断用户是否登录
			// 如果已登录，把用户浏览的水果信息存入cookie
			setCookie(request, response, shuiguo.getId() + "");
		}

		return mapping.findForward("info");

	}

	// 设置用户浏览过水果信息
	public void setCookie(HttpServletRequest request,
			HttpServletResponse response, String rid) {

		Cookie cookies[] = request.getCookies();
		String shuiguoList = "";
		String iscookie = "n";
		int uid = ((Users) request.getSession().getAttribute("users")).getUid();// 获得当前登录用户id
		String cookieName = "shuiguoList" + uid; // 设置cookie名
		Cookie cookie = null;
		if (cookies != null) {
			for (Cookie c : cookies) {
				if (c.getName().equals(cookieName)) { // 找到该cookie对象
					cookie = c;

					shuiguoList = cookie.getValue();
					String strs[] = shuiguoList.split(",");
					String isrid = "n";
					for (String str : strs) {
						if (str.equals(rid)) {
							isrid = "y";
							break;
						}
					}

					if (isrid.equals("n")) {
						shuiguoList = rid + "," + shuiguoList;
						cookie.setValue(shuiguoList);
						response.addCookie(cookie);
						iscookie = "y";
						break;
					}
				}
			}
		}
		if (iscookie.equals("n")) { // 没有找到对应cookie对象,创建一个新的
			shuiguoList = rid;
			cookie = new Cookie(cookieName, shuiguoList);
			cookie.setMaxAge(60 * 60 * 24 * 15); // 设置cookie的有效存活期为15天
			cookie.setPath("/");
			response.addCookie(cookie);

		}
	}

	// 获得出租水果信息(修改)
	public ActionForward getShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoForm leaseShuiguoForm = (LeaseShuiguoForm) form;

		Leaseshuiguo shuiguo = getisShuiguo(form, request, response); // 获得水果信息及图片
		sel(request, response);
		String esthment = shuiguo.getEsthment();
		BeanUtils.copyProperties(leaseShuiguoForm, shuiguo); // 复制javaBean属性

		if (esthment != null && !esthment.equals("")) {
			String esthments[] = esthment.split(",");
			leaseShuiguoForm.setEsthments(esthments);
		}
		leaseShuiguoForm.setAreaId(shuiguo.getAreaType().getGid());
		leaseShuiguoForm.setHtypeId(shuiguo.getShuiguoType().getId());

		return mapping.findForward("update");

	}

	// 修改
	public ActionForward updateShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoForm leaseform = (LeaseShuiguoForm) form;

		LeaseShuiguoServer lserver = new LeaseShuiguoServerImpl();
		AreaTypeServer aserver = new AreaTypeServerImpl();
		ShuiguoTypeServer hserver = new ShuiguoTypeServerimpl();
		UserServer user = new UserServerImpl();

		Users users = (Users) request.getSession().getAttribute("users");// 获得当前用户
		Leaseshuiguo shuiguo = lserver.getShuiguo(leaseform.getId()); // 加载出所要修改的水果

		BeanUtils.copyProperties(shuiguo, leaseform); // 复制javaBean属性
		shuiguo.setAreaType(aserver.getthis(leaseform.getAreaId())); // 加载并设置一个区域对象
		shuiguo.setShuiguoType(hserver.getShuiguo_type(leaseform.getHtypeId())); // 加载并设置一个水果类别对象
		// 水果基础设施
		if (leaseform.getEsthments() != null) {
			String esthment = "";
			for (String ment : leaseform.getEsthments()) {
				esthment += ment + ",";
			}
			esthment = esthment.substring(0, esthment.length() - 1);
			shuiguo.setEsthment(esthment);
		}

		shuiguo.setTime(new Date().toLocaleString());
		shuiguo.setState(1);

		// 判断用户联系方式是否有改变
		if (!users.getPhone().equals(leaseform.getTelePhone())
				|| !users.getEmail().endsWith(leaseform.getEmail())) {
			// 有改变，修改当前用户信息
			users.setPhone(leaseform.getTelePhone());
			users.setEmail(leaseform.getEmail());
			user.update(users);
		}
		boolean isshuiguo = false;
		boolean isimg = true;
		int isimgCount = 0;

		// 获得上传文件保存在服务器上的文件夹路径
		String path = this.servlet.getServletContext()
				.getRealPath("/uploadIMG");

		for (int i = 0; i < leaseform.getFile().length; i++) {
			FormFile file = leaseform.getFile()[i];
			if (file != null && !file.getFileName().equals("")) { // 需要上传图片的情况

				String date = new SimpleDateFormat("yyyyMMddhhmmss")
						.format(new Date());
				String fileName = file.getFileName(); // 获得上传文件名
				fileName = users.getUname() + "_" + date
						+ fileName.substring(fileName.lastIndexOf(".")); // 重命名上传文件名

				if (isimgCount == 0) {
					shuiguo.setImg(fileName); // 设置封面
					isshuiguo = lserver.update(shuiguo);// 修改该条水果信息
				}
				if (!isshuiguo) { // 水果信息修改失败，停止图片上传
					break;
				}
				// 获得上传文件数据
				byte[] data = file.getFileData();
				// 创建文件对象
				File uploadFile = new File(path + "\\" + fileName);
				// 创建文件输出流
				FileOutputStream stream = new FileOutputStream(uploadFile);
				stream.write(data);

				// 添加图片到数据库表
				ImageTableServer iserver = new ImageTableServerImpl();
				ImageTable image = new ImageTable();
				image.setImage(fileName);
				image.setLeaseShuiguo(shuiguo);
				if (!iserver.add(image)) { // 添加图片出错
					isimg = false;
					break;
				} else {
					isimgCount++; // 添加的图片数
				}

			}
		}

		if (isimgCount == 0) {// 不需要上传图片的情况，
			shuiguo.setImg("");
			isshuiguo = lserver.update(shuiguo);// 直接修改该条水果信息
		}

		if (isshuiguo && isimg) {
			if (isimgCount == 0) { // 没有上传图片
				response.getWriter().print("<script>");
				response.getWriter().print("alert('出售水果修改成功！');");
				response.getWriter().print("window.location='shuiguo.jsp';");
				response.getWriter().print("</script>");

			} else { // 图片全部成功上传
				response.getWriter().print("<script>");
				response.getWriter().print("alert('出售水果修改成功！图片已被成功上传');");
				response.getWriter().print("window.location='shuiguo.jsp';");
				response.getWriter().print("</script>");
			}

		} else if (isshuiguo && isimg == false && isimgCount > 0) { // 部分图片上传成功
			response.getWriter().print("<script>");
			response.getWriter().print(
					"alert('出售水果修改成功！" + isimgCount + "张图片已被成功上传');");
			response.getWriter().print("window.location='shuiguo.jsp';");
			response.getWriter().print("</script>");
		} else if (isshuiguo && isimg == false && isimgCount == 0) { // 图片上传失败
			response.getWriter().print("<script>");
			response.getWriter().print("alert('出售水果修改成功！图片上传失败');");
			response.getWriter().print("window.location='shuiguo.jsp';");
			response.getWriter().print("</script>");
		} else { // 发布销售水果失败(图片不被地传)
			response.getWriter().print("<script>");
			response.getWriter().print("alert('出售水果修改失败，请重新再试！');");
			response.getWriter().print("window.history.go(-1);");
			response.getWriter().print("</script>");
		}

		return null;
	}

	public ActionForward delShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException,
			FileNotFoundException, IOException {
		LeaseShuiguoForm leaseform = (LeaseShuiguoForm) form;
		LeaseShuiguoServer server = new LeaseShuiguoServerImpl();

		String fromto = leaseform.getFromto();

		int id = leaseform.getId(); // 获得所要删除的水果id

		boolean flag = false;

		if (fromto != null && fromto.equals("admin")) { // 后台管理员删除
			Leaseshuiguo shuiguo = server.getShuiguo(id);
			shuiguo.setState(2);          //修改状态为审核未通过
			flag = server.update(shuiguo);
		}// 前台用户删除
		else {
			flag = server.delShuiguo(id);
		}

		if (!flag) {
			response.getWriter().print("<script>");
			response.getWriter().print("alert('水果删除失败，请重新再试！');");
			response.getWriter().print("window.history.go(-1);");
			response.getWriter().print("</script>");
			return null;
		} else {
			response.getWriter().print("<script>");
			
			if(fromto != null && fromto.equals("admin")){  //返回后台管理
				response.getWriter().print("window.location='leaseShuiguo.do?method=showShuiguoAdmin&showPage=1';");
			}else{     
				//返回前台用户管理
				response.getWriter().print("window.location='leaseShuiguo.do?method=showShuiguo&showPage=1';");
			}
			
			response.getWriter().print("</script>");
			return null;
		}
	}
}