/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.nio.MappedByteBuffer;
import java.util.List;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import entity.ShuiguoType;

import server.ShuiguoTypeServer;
import server.impl.ShuiguoTypeServerimpl;
import struts.form.ShuiguoTypeForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-22-2010
 * 
 * XDoclet definition:
 * @struts.action path="/shuiguoType" name="shuiguoTypeForm" input="/form/shuiguoType.jsp" parameter="method" scope="request" validate="true"
 */
@Entity public class ShuiguoTypeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addShuiguo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {    //Ìí¼Ó
		ShuiguoTypeForm shuiguoTypeForm = (ShuiguoTypeForm) form;
		
		String htype=shuiguoTypeForm.getType();
		ShuiguoType housType=new ShuiguoType();
		
		housType.setType(htype);
		
		ShuiguoTypeServer shuiguoTypeServer=new ShuiguoTypeServerimpl();
		
		shuiguoTypeServer.insert(housType);
		
		return selectShuiguo_type(mapping, form, request, response);
	}
	
	
	public ActionForward deleteShuiguo_type(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {   //É¾³ý
		ShuiguoTypeForm shuiguoTypeForm = (ShuiguoTypeForm) form;
		int id=Integer.parseInt(request.getParameter("id"));
        ShuiguoTypeServer shuiguoTypeServer=new ShuiguoTypeServerimpl();
		
		shuiguoTypeServer.delObj(id);
		
		return selectShuiguo_type(mapping, form, request, response);
		
	}
	
	
	
	public ActionForward selectShuiguo_type(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {   //²éÑ¯
		ShuiguoTypeForm shuiguoTypeForm = (ShuiguoTypeForm) form;
		
		ShuiguoTypeServer  typeServer=new ShuiguoTypeServerimpl();
		
		List<ShuiguoType> hlist=typeServer.select();
		
		request.setAttribute("hlist", hlist);
		
		return mapping.findForward("show");
	}
}